version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/node/app  # Monta tu proyecto local en el contenedor
      - /home/node/app/node_modules  # Ignora los node_modules del host
    ports:
      - "9100:3000"  # Expone el puerto 3000
    command: ["yarn", "start"]  # Mantén el servidor de desarrollo activo